/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'displayOrder', 'iconUrl', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayOrder: number | null
  @column()
  declare iconUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventSchema extends BaseModel {
  static $columns = ['categoryId', 'coverImageUrl', 'createdAt', 'description', 'endDate', 'galleryImages', 'id', 'isFeatured', 'organizerId', 'publishedAt', 'seoMeta', 'slug', 'startDate', 'status', 'title', 'updatedAt', 'venueAddress', 'venueCoordinates', 'venueName'] as const
  $columns = EventSchema.$columns
  @column()
  declare categoryId: string | null
  @column()
  declare coverImageUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.dateTime()
  declare endDate: DateTime | null
  @column()
  declare galleryImages: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean | null
  @column()
  declare organizerId: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare seoMeta: any | null
  @column()
  declare slug: string
  @column.dateTime()
  declare startDate: DateTime
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare venueAddress: string | null
  @column()
  declare venueCoordinates: any | null
  @column()
  declare venueName: string | null
}

export class ProfileSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'firstName', 'id', 'lastName', 'locale', 'phoneNumber', 'timezone', 'updatedAt', 'userId', 'whatsappOptIn'] as const
  $columns = ProfileSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastName: string | null
  @column()
  declare locale: string | null
  @column()
  declare phoneNumber: string | null
  @column()
  declare timezone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare whatsappOptIn: boolean | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'permissions', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare permissions: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TicketTypeSchema extends BaseModel {
  static $columns = ['basePrice', 'createdAt', 'currency', 'description', 'eventId', 'id', 'maxPerOrder', 'name', 'quantityReserved', 'quantitySold', 'quantityTotal', 'salesEndAt', 'salesStartAt', 'sortOrder', 'status', 'updatedAt'] as const
  $columns = TicketTypeSchema.$columns
  @column()
  declare basePrice: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string | null
  @column()
  declare description: string | null
  @column()
  declare eventId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maxPerOrder: number | null
  @column()
  declare name: string
  @column()
  declare quantityReserved: number | null
  @column()
  declare quantitySold: number | null
  @column()
  declare quantityTotal: number
  @column.dateTime()
  declare salesEndAt: DateTime | null
  @column.dateTime()
  declare salesStartAt: DateTime | null
  @column()
  declare sortOrder: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'emailVerifiedAt', 'fullName', 'googleId', 'googleRefreshToken', 'id', 'password', 'roleId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column()
  declare googleId: string | null
  @column()
  declare googleRefreshToken: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare roleId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
