/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CategorySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'displayOrder',
    'iconUrl',
    'id',
    'name',
    'slug',
    'updatedAt',
  ] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayOrder: number | null
  @column()
  declare iconUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CurrencySchema extends BaseModel {
  static $columns = [
    'code',
    'countryCode',
    'createdAt',
    'exchangeRate',
    'id',
    'isActive',
    'name',
    'networks',
    'sortOrder',
    'symbol',
    'updatedAt',
  ] as const
  $columns = CurrencySchema.$columns
  @column()
  declare code: string
  @column()
  declare countryCode: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare exchangeRate: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare networks: any
  @column()
  declare sortOrder: number
  @column()
  declare symbol: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventBoostSchema extends BaseModel {
  static $columns = [
    'budget',
    'budgetType',
    'callToAction',
    'channels',
    'createdAt',
    'currency',
    'endDate',
    'eventId',
    'failureReason',
    'feeRuleId',
    'headline',
    'id',
    'lastSyncedAt',
    'markupAmount',
    'metaAdAccountId',
    'metaAdId',
    'metaAdsetId',
    'metaBudget',
    'metaCampaignId',
    'metaClicks',
    'metaCpc',
    'metaCtr',
    'metaImpressions',
    'metaSpent',
    'organizerId',
    'paymentReference',
    'paymentStatus',
    'primaryText',
    'startDate',
    'status',
    'targetAudience',
    'updatedAt',
  ] as const
  $columns = EventBoostSchema.$columns
  @column()
  declare budget: string
  @column()
  declare budgetType: string
  @column()
  declare callToAction: string | null
  @column()
  declare channels: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string | null
  @column.dateTime()
  declare endDate: DateTime | null
  @column()
  declare eventId: string
  @column()
  declare failureReason: string | null
  @column()
  declare feeRuleId: string | null
  @column()
  declare headline: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare markupAmount: string | null
  @column()
  declare metaAdAccountId: string | null
  @column()
  declare metaAdId: string | null
  @column()
  declare metaAdsetId: string | null
  @column()
  declare metaBudget: string
  @column()
  declare metaCampaignId: string | null
  @column()
  declare metaClicks: number | null
  @column()
  declare metaCpc: string | null
  @column()
  declare metaCtr: string | null
  @column()
  declare metaImpressions: number | null
  @column()
  declare metaSpent: string | null
  @column()
  declare organizerId: number
  @column()
  declare paymentReference: string | null
  @column()
  declare paymentStatus: string | null
  @column()
  declare primaryText: string | null
  @column.dateTime()
  declare startDate: DateTime
  @column()
  declare status: string
  @column()
  declare targetAudience: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventFeeRuleSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'effectiveFrom',
    'effectiveUntil',
    'eventId',
    'feeRuleId',
    'id',
    'overrideValue',
    'updatedAt',
  ] as const
  $columns = EventFeeRuleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveFrom: DateTime | null
  @column.dateTime()
  declare effectiveUntil: DateTime | null
  @column()
  declare eventId: string
  @column()
  declare feeRuleId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare overrideValue: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventSchema extends BaseModel {
  static $columns = [
    'categoryId',
    'coverImageUrl',
    'createdAt',
    'currency',
    'description',
    'endDate',
    'frozenAt',
    'galleryImages',
    'id',
    'isFeatured',
    'isFrozen',
    'organizerId',
    'publishedAt',
    'seoMeta',
    'slug',
    'startDate',
    'status',
    'title',
    'updatedAt',
    'venueAddress',
    'venueCoordinates',
    'venueName',
  ] as const
  $columns = EventSchema.$columns
  @column()
  declare categoryId: string | null
  @column()
  declare coverImageUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string | null
  @column()
  declare description: string | null
  @column.dateTime()
  declare endDate: DateTime | null
  @column.dateTime()
  declare frozenAt: DateTime | null
  @column()
  declare galleryImages: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean | null
  @column()
  declare isFrozen: boolean
  @column()
  declare organizerId: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare seoMeta: any | null
  @column()
  declare slug: string
  @column.dateTime()
  declare startDate: DateTime
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare venueAddress: string | null
  @column()
  declare venueCoordinates: any | null
  @column()
  declare venueName: string | null
}

export class FeeRuleSchema extends BaseModel {
  static $columns = [
    'appliesTo',
    'buyerPercentage',
    'createdAt',
    'id',
    'isDefault',
    'maxFee',
    'minFee',
    'name',
    'organizerPercentage',
    'priority',
    'secondaryValue',
    'status',
    'type',
    'updatedAt',
    'value',
  ] as const
  $columns = FeeRuleSchema.$columns
  @column()
  declare appliesTo: string
  @column()
  declare buyerPercentage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean | null
  @column()
  declare maxFee: string | null
  @column()
  declare minFee: string | null
  @column()
  declare name: string
  @column()
  declare organizerPercentage: string | null
  @column()
  declare priority: number | null
  @column()
  declare secondaryValue: string | null
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class NotificationLogSchema extends BaseModel {
  static $columns = [
    'channel',
    'createdAt',
    'deliveredAt',
    'errorDetails',
    'externalMessageId',
    'id',
    'payload',
    'readAt',
    'recipientIdentifier',
    'recipientType',
    'sentAt',
    'status',
    'templateId',
    'updatedAt',
  ] as const
  $columns = NotificationLogSchema.$columns
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare errorDetails: any | null
  @column()
  declare externalMessageId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare payload: any | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare recipientIdentifier: string | null
  @column()
  declare recipientType: string
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare templateId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderItemSchema extends BaseModel {
  static $columns = [
    'attendeeDetails',
    'createdAt',
    'id',
    'lineTotal',
    'orderId',
    'quantity',
    'ticketTypeId',
    'unitPrice',
    'updatedAt',
  ] as const
  $columns = OrderItemSchema.$columns
  @column()
  declare attendeeDetails: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lineTotal: string
  @column()
  declare orderId: string
  @column()
  declare quantity: number
  @column()
  declare ticketTypeId: string | null
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = [
    'buyerId',
    'cancellationReason',
    'createdAt',
    'currency',
    'guestEmail',
    'guestName',
    'guestPhone',
    'id',
    'ipAddress',
    'mbiyopayAuthMode',
    'orderNumber',
    'organizerNetAmount',
    'paidAt',
    'paymentIntentId',
    'paymentMethod',
    'paymentProcessorFee',
    'platformFeeAmount',
    'refundedAt',
    'status',
    'totalGrossAmount',
    'updatedAt',
    'userAgent',
  ] as const
  $columns = OrderSchema.$columns
  @column()
  declare buyerId: number | null
  @column()
  declare cancellationReason: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string | null
  @column()
  declare guestEmail: string | null
  @column()
  declare guestName: string | null
  @column()
  declare guestPhone: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare mbiyopayAuthMode: string | null
  @column()
  declare orderNumber: string
  @column()
  declare organizerNetAmount: string | null
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare paymentIntentId: string | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare paymentProcessorFee: string | null
  @column()
  declare platformFeeAmount: string | null
  @column.dateTime()
  declare refundedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare totalGrossAmount: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
}

export class OrganizerFeeProfileSchema extends BaseModel {
  static $columns = [
    'contractEndDate',
    'contractStartDate',
    'createdAt',
    'feeRuleId',
    'id',
    'organizerId',
    'updatedAt',
  ] as const
  $columns = OrganizerFeeProfileSchema.$columns
  @column.dateTime()
  declare contractEndDate: DateTime | null
  @column.dateTime()
  declare contractStartDate: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feeRuleId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizerId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PayoutSchema extends BaseModel {
  static $columns = [
    'adminNotes',
    'amount',
    'beneficiary',
    'completedAt',
    'createdAt',
    'currency',
    'eventId',
    'id',
    'mbiyopayStatus',
    'network',
    'organizerId',
    'payoutMethod',
    'payoutReference',
    'phoneNumber',
    'processedAt',
    'requestedAt',
    'status',
    'transactionId',
    'updatedAt',
  ] as const
  $columns = PayoutSchema.$columns
  @column()
  declare adminNotes: string | null
  @column()
  declare amount: string
  @column()
  declare beneficiary: string | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string | null
  @column()
  declare eventId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mbiyopayStatus: string | null
  @column()
  declare network: string | null
  @column()
  declare organizerId: number
  @column()
  declare payoutMethod: string | null
  @column()
  declare payoutReference: string | null
  @column()
  declare phoneNumber: string | null
  @column.dateTime()
  declare processedAt: DateTime | null
  @column.dateTime()
  declare requestedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare transactionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PlatformRevenueLogSchema extends BaseModel {
  static $columns = [
    'calculatedFeeAmount',
    'collectedAt',
    'createdAt',
    'feeBreakdown',
    'feeRuleId',
    'id',
    'orderId',
    'updatedAt',
  ] as const
  $columns = PlatformRevenueLogSchema.$columns
  @column()
  declare calculatedFeeAmount: string
  @column.dateTime()
  declare collectedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feeBreakdown: any | null
  @column()
  declare feeRuleId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProfileSchema extends BaseModel {
  static $columns = [
    'avatarUrl',
    'createdAt',
    'firstName',
    'id',
    'lastName',
    'locale',
    'phoneNumber',
    'timezone',
    'updatedAt',
    'userId',
    'whatsappOptIn',
  ] as const
  $columns = ProfileSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastName: string | null
  @column()
  declare locale: string | null
  @column()
  declare phoneNumber: string | null
  @column()
  declare timezone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare whatsappOptIn: boolean | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'permissions', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare permissions: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TicketInventoryLockSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'expiresAt',
    'id',
    'quantity',
    'sessionId',
    'ticketTypeId',
    'userId',
  ] as const
  $columns = TicketInventoryLockSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare quantity: number
  @column()
  declare sessionId: string | null
  @column()
  declare ticketTypeId: string
  @column()
  declare userId: number | null
}

export class TicketTypeSchema extends BaseModel {
  static $columns = [
    'basePrice',
    'createdAt',
    'currency',
    'description',
    'eventId',
    'id',
    'maxPerOrder',
    'name',
    'quantityReserved',
    'quantitySold',
    'quantityTotal',
    'salesEndAt',
    'salesStartAt',
    'sortOrder',
    'status',
    'updatedAt',
  ] as const
  $columns = TicketTypeSchema.$columns
  @column()
  declare basePrice: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string | null
  @column()
  declare description: string | null
  @column()
  declare eventId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maxPerOrder: number | null
  @column()
  declare name: string
  @column()
  declare quantityReserved: number | null
  @column()
  declare quantitySold: number | null
  @column()
  declare quantityTotal: number
  @column.dateTime()
  declare salesEndAt: DateTime | null
  @column.dateTime()
  declare salesStartAt: DateTime | null
  @column()
  declare sortOrder: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TicketSchema extends BaseModel {
  static $columns = [
    'checkedInAt',
    'createdAt',
    'eventId',
    'id',
    'orderItemId',
    'pdfUrl',
    'qrToken',
    'status',
    'ticketNumber',
    'ticketTypeId',
    'updatedAt',
    'usedAt',
    'usedByScannerId',
    'uuid',
  ] as const
  $columns = TicketSchema.$columns
  @column.dateTime()
  declare checkedInAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderItemId: string
  @column()
  declare pdfUrl: string | null
  @column()
  declare qrToken: string
  @column()
  declare status: string
  @column()
  declare ticketNumber: string
  @column()
  declare ticketTypeId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare usedByScannerId: number | null
  @column()
  declare uuid: string
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'email',
    'emailVerifiedAt',
    'fullName',
    'googleId',
    'googleRefreshToken',
    'id',
    'isShadow',
    'password',
    'roleId',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column()
  declare googleId: string | null
  @column()
  declare googleRefreshToken: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isShadow: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare roleId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WhatsappTemplateSchema extends BaseModel {
  static $columns = [
    'category',
    'createdAt',
    'id',
    'languageCode',
    'metaTemplateId',
    'name',
    'status',
    'updatedAt',
    'variables',
  ] as const
  $columns = WhatsappTemplateSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare languageCode: string | null
  @column()
  declare metaTemplateId: string | null
  @column()
  declare name: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare variables: any | null
}
